// <auto-generated />
using System;
using Awaver.Backend.Data;
using Awaver.Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Awaver.Backend.Migrations
{
    [DbContext(typeof(AwaverDbContext))]
    [Migration("20260714000001_AddVideoTimeSecToDrowsinessScores")]
    partial class AddVideoTimeSecToDrowsinessScores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "drowsiness_level", new[] { "caution", "danger", "normal", "warning" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Awaver.Backend.Models.Admin", b =>
                {
                    b.Property<string>("AdminId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("admin_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("AdminId");

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("Awaver.Backend.Models.AnalysisEventOutbox", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("EventId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("SessionId");

                    b.HasIndex("DeliveredAt", "NextAttemptAt");

                    b.ToTable("analysis_event_outbox", (string)null);
                });

            modelBuilder.Entity("Awaver.Backend.Models.AuthSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<DateTimeOffset>("IdleExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("idle_expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("principal_id");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("principal_type");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("SessionId");

                    b.HasIndex("PrincipalType", "PrincipalId");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("Awaver.Backend.Models.Calibration", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("CalibratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calibrated_at");

                    b.Property<decimal>("EarOpen")
                        .HasPrecision(12, 8)
                        .HasColumnType("numeric(12,8)")
                        .HasColumnName("ear_open");

                    b.Property<decimal>("EarThreshold")
                        .HasPrecision(12, 8)
                        .HasColumnType("numeric(12,8)")
                        .HasColumnName("ear_threshold");

                    b.Property<long>("SourceSequenceNo")
                        .HasColumnType("bigint")
                        .HasColumnName("source_sequence_no");

                    b.Property<int>("TotalFrames")
                        .HasColumnType("integer")
                        .HasColumnName("total_frames");

                    b.Property<int>("ValidFrames")
                        .HasColumnType("integer")
                        .HasColumnName("valid_frames");

                    b.HasKey("SessionId");

                    b.ToTable("calibrations", (string)null);
                });

            modelBuilder.Entity("Awaver.Backend.Models.DrowsinessScore", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<long>("SourceSequenceNo")
                        .HasColumnType("bigint")
                        .HasColumnName("source_sequence_no");

                    b.Property<decimal>("Ear")
                        .HasPrecision(12, 8)
                        .HasColumnType("numeric(12,8)")
                        .HasColumnName("ear");

                    b.Property<DrowsinessLevel>("Level")
                        .HasColumnType("drowsiness_level")
                        .HasColumnName("level");

                    b.Property<decimal>("Perclos")
                        .HasPrecision(12, 8)
                        .HasColumnType("numeric(12,8)")
                        .HasColumnName("perclos");

                    b.Property<decimal>("PitchDeg")
                        .HasPrecision(12, 8)
                        .HasColumnType("numeric(12,8)")
                        .HasColumnName("pitch_deg");

                    b.Property<decimal>("Score")
                        .HasPrecision(12, 8)
                        .HasColumnType("numeric(12,8)")
                        .HasColumnName("score");

                    b.Property<DateTimeOffset>("ScoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scored_at");

                    b.Property<double?>("VideoTimeSec")
                        .HasColumnType("double precision")
                        .HasColumnName("video_time_sec");

                    b.Property<decimal>("YawDeg")
                        .HasPrecision(12, 8)
                        .HasColumnType("numeric(12,8)")
                        .HasColumnName("yaw_deg");

                    b.HasKey("SessionId", "SourceSequenceNo");

                    b.HasIndex("SessionId", "ScoredAt")
                        .IsUnique();

                    b.ToTable("drowsiness_scores", (string)null);
                });

            modelBuilder.Entity("Awaver.Backend.Models.LearningSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("student_id");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("video_id");

                    b.HasKey("SessionId");

                    b.HasIndex("StudentId");

                    b.HasIndex("VideoId", "StartedAt");

                    b.ToTable("learning_sessions", (string)null);
                });

            modelBuilder.Entity("Awaver.Backend.Models.PlaybackEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<double?>("VideoTimeSec")
                        .HasColumnType("double precision")
                        .HasColumnName("video_time_sec");

                    b.HasKey("EventId");

                    b.HasIndex("SessionId");

                    b.ToTable("playback_events", (string)null);
                });

            modelBuilder.Entity("Awaver.Backend.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("StudentId");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("Awaver.Backend.Models.Teacher", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("teacher_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByAdminId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_admin_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("TeacherId");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("Awaver.Backend.Models.AnalysisEventOutbox", b =>
                {
                    b.HasOne("Awaver.Backend.Models.LearningSession", "LearningSession")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningSession");
                });

            modelBuilder.Entity("Awaver.Backend.Models.Calibration", b =>
                {
                    b.HasOne("Awaver.Backend.Models.LearningSession", "LearningSession")
                        .WithOne()
                        .HasForeignKey("Awaver.Backend.Models.Calibration", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningSession");
                });

            modelBuilder.Entity("Awaver.Backend.Models.DrowsinessScore", b =>
                {
                    b.HasOne("Awaver.Backend.Models.LearningSession", "LearningSession")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningSession");
                });

            modelBuilder.Entity("Awaver.Backend.Models.LearningSession", b =>
                {
                    b.HasOne("Awaver.Backend.Models.Student", "Student")
                        .WithMany("LearningSessions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Awaver.Backend.Models.PlaybackEvent", b =>
                {
                    b.HasOne("Awaver.Backend.Models.LearningSession", "LearningSession")
                        .WithMany("PlaybackEvents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningSession");
                });

            modelBuilder.Entity("Awaver.Backend.Models.LearningSession", b =>
                {
                    b.Navigation("PlaybackEvents");
                });

            modelBuilder.Entity("Awaver.Backend.Models.Student", b =>
                {
                    b.Navigation("LearningSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
