// <auto-generated />
using System;
using Awaver.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Awaver.Backend.Migrations
{
    [DbContext(typeof(AwaverDbContext))]
    [Migration("20260706101359_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Awaver.Backend.Models.LearningSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("student_id");

                    b.HasKey("SessionId");

                    b.HasIndex("StudentId");

                    b.ToTable("learning_sessions", (string)null);
                });

            modelBuilder.Entity("Awaver.Backend.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("StudentId");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("Awaver.Backend.Models.LearningSession", b =>
                {
                    b.HasOne("Awaver.Backend.Models.Student", "Student")
                        .WithMany("LearningSessions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Awaver.Backend.Models.Student", b =>
                {
                    b.Navigation("LearningSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
